-- CarCam Pro initial migration.
-- Run via: pnpm prisma migrate deploy

-- Required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "postgis";

-- The rest of the schema is generated by Prisma on `prisma migrate dev`.
-- This file exists so `postgis` is present before the first geography column
-- is defined. The Prisma migrator auto-generates the remaining DDL on first
-- run in dev; for production deploys, use `prisma migrate deploy` after
-- committing the generated SQL to the `migrations/` directory.
